In [1]:
import pandas as pd

In [9]:
usef = pd.read_csv("combined.csv")
arian = pd.read_csv("result2.csv")

In [10]:
del usef["Unnamed: 0"]

In [12]:
usef

,نام,شهر,رتبه کشوری,رتبه در منطقه,منطقه,سابقه کانونی,میانگین تراز کانون,تعداد آزمون,رشته قبولی,دانشگاه قبولی,رشته,سال کنکور
0,علی محققی,تهران,0,10.0,منطقه يک,2,6617,NaN,NaN,NaN,هنر,1390
1,فرناز شهریاری,اصفهان,6,6.0,منطقه يک,1,7243,0.0,سينما,دانشگاه هنر تهران,هنر,1390
2,احسان غیاثی نسب,اراك,18,2.0,منطقه دو,1,7000,NaN,NaN,NaN,هنر,1390
3,محمدامین شریفی جبلی,كرج,19,3.0,منطقه دو,1,6214,0.0,عکاسي,دانشگاه هنر تهران,هنر,1390
4,ارغوان عبدالملکی,تهران,46,7.0,منطقه دو,1,6352,0.0,سينما,دانشگاه هنر تهران,هنر,1390
...,...,...,...,...,...,...,...,...,...,...,...,...
31322,محسن حسین آبادی,كنگاور,3565,990.0,منطقه 3,2,6200,69.0,دندانپزشکي,دانشگاه علوم پزشکي ايلام,تجربی,1400
31323,مهدی محمدرضائی,رباط كريم,3586,995.0,منطقه 3,7,5952,150.0,پزشکي - بورسيه وزارت دفاع,دانشگاه علوم پزشکي ارتش جمهوري اسلامي ايران,تجربی,1400
31324,احسان قزلباش,اشنويه,3596,999.0,منطقه 3,3,6666,64.0,پزشکي - نيمسال دوم,دانشگاه علوم پزشکي اروميه,تجربی,1400
31325,محمد ملائی,گنبد,3596,999.0,منطقه 3,3,6474,60.0,پزشکي,دانشگاه علوم پزشکي بابل,تجربی,1400
31326,محمد الهویی نظری,گرگان,3596,999.0,منطقه 3,1,6132,30.0,دندانپزشکي,دانشگاه علوم پزشکي بوشهر,تجربی,1400

In [11]:
arian

,نام و نام خانوادگی,شهر,رتبه کشوری,رتبه در منطقه,منطقه,سابقه کانونی,میانگین تراز کانون,تعداد آزمون,رشته قبولی,دانشگاه قبولی,رشته مدرسه,سال
0,محمد پیام تائبی,تهران,1,1.0,منطقه 1,3,7738,72,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
1,محمدشایان شعبانی,رفسنجان,2,1.0,منطقه 2,6,7857,120,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
2,محمد اسماعیلی,اراك,3,2.0,منطقه 2,7,7589,142,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
3,امیرمهدی میقانی,اراك,5,4.0,منطقه 2,3,7529,79,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
4,ترانه خسروجردی,مشهد,6,2.0,منطقه 1,1,7645,23,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
...,...,...,...,...,...,...,...,...,...,...,...,...
47345,فرشاد ابراهیمی,تربت جام,138,6.0,منطقه سه,2,7090,0,مهندسي شيمي,دانشگاه صنعتي شريف - تهران,زبان,1390
47346,علی احمدی شاهرخت,قائن,179,7.0,منطقه سه,3,7289,0,مهندسي صنايع,دانشگاه صنعتي شريف - تهران,زبان,1390
47347,محمدامین شیخی,گچساران,183,8.0,منطقه سه,6,7326,0,مهندسي برق,دانشگاه علم و صنعت ايران - تهران,زبان,1390
47348,ابوالفضل سیرفر,جيرفت,206,9.0,منطقه سه,3,7733,0,مهندسي عمران,دانشگاه صنعتي شريف - تهران,زبان,1390
47349,عمادالدین محرابیان,مهريز,217,10.0,منطقه سه,6,7001,0,پزشکي,دانشگاه علوم پزشکي شيراز,زبان,1390

In [13]:
usef = usef.rename(columns={'سال کنکور': 'سال', 'رشته': 'رشته مدرسه',"نام":"نام و نام خانوادگی"})

In [14]:
usef

,نام و نام خانوادگی,شهر,رتبه کشوری,رتبه در منطقه,منطقه,سابقه کانونی,میانگین تراز کانون,تعداد آزمون,رشته قبولی,دانشگاه قبولی,رشته مدرسه,سال
0,علی محققی,تهران,0,10.0,منطقه يک,2,6617,NaN,NaN,NaN,هنر,1390
1,فرناز شهریاری,اصفهان,6,6.0,منطقه يک,1,7243,0.0,سينما,دانشگاه هنر تهران,هنر,1390
2,احسان غیاثی نسب,اراك,18,2.0,منطقه دو,1,7000,NaN,NaN,NaN,هنر,1390
3,محمدامین شریفی جبلی,كرج,19,3.0,منطقه دو,1,6214,0.0,عکاسي,دانشگاه هنر تهران,هنر,1390
4,ارغوان عبدالملکی,تهران,46,7.0,منطقه دو,1,6352,0.0,سينما,دانشگاه هنر تهران,هنر,1390
...,...,...,...,...,...,...,...,...,...,...,...,...
31322,محسن حسین آبادی,كنگاور,3565,990.0,منطقه 3,2,6200,69.0,دندانپزشکي,دانشگاه علوم پزشکي ايلام,تجربی,1400
31323,مهدی محمدرضائی,رباط كريم,3586,995.0,منطقه 3,7,5952,150.0,پزشکي - بورسيه وزارت دفاع,دانشگاه علوم پزشکي ارتش جمهوري اسلامي ايران,تجربی,1400
31324,احسان قزلباش,اشنويه,3596,999.0,منطقه 3,3,6666,64.0,پزشکي - نيمسال دوم,دانشگاه علوم پزشکي اروميه,تجربی,1400
31325,محمد ملائی,گنبد,3596,999.0,منطقه 3,3,6474,60.0,پزشکي,دانشگاه علوم پزشکي بابل,تجربی,1400
31326,محمد الهویی نظری,گرگان,3596,999.0,منطقه 3,1,6132,30.0,دندانپزشکي,دانشگاه علوم پزشکي بوشهر,تجربی,1400

In [15]:
final = pd.concat([arian,usef],axis=0)

In [16]:
final

,نام و نام خانوادگی,شهر,رتبه کشوری,رتبه در منطقه,منطقه,سابقه کانونی,میانگین تراز کانون,تعداد آزمون,رشته قبولی,دانشگاه قبولی,رشته مدرسه,سال
0,محمد پیام تائبی,تهران,1,1.0,منطقه 1,3,7738,72.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
1,محمدشایان شعبانی,رفسنجان,2,1.0,منطقه 2,6,7857,120.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
2,محمد اسماعیلی,اراك,3,2.0,منطقه 2,7,7589,142.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
3,امیرمهدی میقانی,اراك,5,4.0,منطقه 2,3,7529,79.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
4,ترانه خسروجردی,مشهد,6,2.0,منطقه 1,1,7645,23.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
...,...,...,...,...,...,...,...,...,...,...,...,...
31322,محسن حسین آبادی,كنگاور,3565,990.0,منطقه 3,2,6200,69.0,دندانپزشکي,دانشگاه علوم پزشکي ايلام,تجربی,1400
31323,مهدی محمدرضائی,رباط كريم,3586,995.0,منطقه 3,7,5952,150.0,پزشکي - بورسيه وزارت دفاع,دانشگاه علوم پزشکي ارتش جمهوري اسلامي ايران,تجربی,1400
31324,احسان قزلباش,اشنويه,3596,999.0,منطقه 3,3,6666,64.0,پزشکي - نيمسال دوم,دانشگاه علوم پزشکي اروميه,تجربی,1400
31325,محمد ملائی,گنبد,3596,999.0,منطقه 3,3,6474,60.0,پزشکي,دانشگاه علوم پزشکي بابل,تجربی,1400
31326,محمد الهویی نظری,گرگان,3596,999.0,منطقه 3,1,6132,30.0,دندانپزشکي,دانشگاه علوم پزشکي بوشهر,تجربی,1400

In [17]:
final = final.dropna()

In [18]:
final

,نام و نام خانوادگی,شهر,رتبه کشوری,رتبه در منطقه,منطقه,سابقه کانونی,میانگین تراز کانون,تعداد آزمون,رشته قبولی,دانشگاه قبولی,رشته مدرسه,سال
0,محمد پیام تائبی,تهران,1,1.0,منطقه 1,3,7738,72.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
1,محمدشایان شعبانی,رفسنجان,2,1.0,منطقه 2,6,7857,120.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
2,محمد اسماعیلی,اراك,3,2.0,منطقه 2,7,7589,142.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
3,امیرمهدی میقانی,اراك,5,4.0,منطقه 2,3,7529,79.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
4,ترانه خسروجردی,مشهد,6,2.0,منطقه 1,1,7645,23.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
...,...,...,...,...,...,...,...,...,...,...,...,...
31322,محسن حسین آبادی,كنگاور,3565,990.0,منطقه 3,2,6200,69.0,دندانپزشکي,دانشگاه علوم پزشکي ايلام,تجربی,1400
31323,مهدی محمدرضائی,رباط كريم,3586,995.0,منطقه 3,7,5952,150.0,پزشکي - بورسيه وزارت دفاع,دانشگاه علوم پزشکي ارتش جمهوري اسلامي ايران,تجربی,1400
31324,احسان قزلباش,اشنويه,3596,999.0,منطقه 3,3,6666,64.0,پزشکي - نيمسال دوم,دانشگاه علوم پزشکي اروميه,تجربی,1400
31325,محمد ملائی,گنبد,3596,999.0,منطقه 3,3,6474,60.0,پزشکي,دانشگاه علوم پزشکي بابل,تجربی,1400
31326,محمد الهویی نظری,گرگان,3596,999.0,منطقه 3,1,6132,30.0,دندانپزشکي,دانشگاه علوم پزشکي بوشهر,تجربی,1400

In [19]:
final = final.reset_index(drop=True)

In [20]:
final

,نام و نام خانوادگی,شهر,رتبه کشوری,رتبه در منطقه,منطقه,سابقه کانونی,میانگین تراز کانون,تعداد آزمون,رشته قبولی,دانشگاه قبولی,رشته مدرسه,سال
0,محمد پیام تائبی,تهران,1,1.0,منطقه 1,3,7738,72.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
1,محمدشایان شعبانی,رفسنجان,2,1.0,منطقه 2,6,7857,120.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
2,محمد اسماعیلی,اراك,3,2.0,منطقه 2,7,7589,142.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
3,امیرمهدی میقانی,اراك,5,4.0,منطقه 2,3,7529,79.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
4,ترانه خسروجردی,مشهد,6,2.0,منطقه 1,1,7645,23.0,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,ریاضی,1400
...,...,...,...,...,...,...,...,...,...,...,...,...
73833,محسن حسین آبادی,كنگاور,3565,990.0,منطقه 3,2,6200,69.0,دندانپزشکي,دانشگاه علوم پزشکي ايلام,تجربی,1400
73834,مهدی محمدرضائی,رباط كريم,3586,995.0,منطقه 3,7,5952,150.0,پزشکي - بورسيه وزارت دفاع,دانشگاه علوم پزشکي ارتش جمهوري اسلامي ايران,تجربی,1400
73835,احسان قزلباش,اشنويه,3596,999.0,منطقه 3,3,6666,64.0,پزشکي - نيمسال دوم,دانشگاه علوم پزشکي اروميه,تجربی,1400
73836,محمد ملائی,گنبد,3596,999.0,منطقه 3,3,6474,60.0,پزشکي,دانشگاه علوم پزشکي بابل,تجربی,1400
73837,محمد الهویی نظری,گرگان,3596,999.0,منطقه 3,1,6132,30.0,دندانپزشکي,دانشگاه علوم پزشکي بوشهر,تجربی,1400

In [22]:
del final["نام و نام خانوادگی"]
final.to_csv("final.csv",index=False)