In [58]:
import pandas as pd
import pickle
import numpy as np

In [64]:
with open("dic_gc1","rb") as f:
    dic_riazi = pickle.load(f)
with open("dic_gc5","rb") as f:
    dic_ensani = pickle.load(f)
with open("dic_gc9","rb") as f:
    dic_zaban = pickle.load(f)

In [65]:
df_riazi = pd.DataFrame.from_dict(dic_riazi.values())
df_ensani = pd.DataFrame.from_dict(dic_ensani.values())
df_zaban = pd.DataFrame.from_dict(dic_zaban.values())

In [ ]:
frames = [df_riazi,df_ensani,df_zaban]

In [61]:
df = df.drop_duplicates()
df = df.reset_index(drop=True)

In [62]:
df = df[~(pd.isnull(df["نام و نام خانوادگی"]))]

In [63]:
df

,نام و نام خانوادگی,شهر,رتبه کشوری,رتبه در منطقه,منطقه,سابقه کانونی,میانگین تراز کانون,تعداد آزمون,رشته قبولی,دانشگاه قبولی,gc,year
1,علیرضا سخایی راد,اهواز,1,1,منطقه 2,5,8283,73,مهندسي برق,دانشگاه صنعتي شريف - تهران,1,100
2,محمدصادق مجیدی یزدی,تهران,2,1,منطقه 1,1,8173,11,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,1,100
3,دانا افاضلی,تهران,3,,,1,7585,5,,,1,100
4,آریا جلالی,لاهيجان,4,2,منطقه 2,3,7808,46,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,1,100
5,علی عباسی,شهركرد,5,3,منطقه 2,1,7482,17,مهندسي کامپيوتر,دانشگاه صنعتي شريف - تهران,1,100
...,...,...,...,...,...,...,...,...,...,...,...,...
18426,امید جمالی,بندر دير,10784,989,منطقه 3,2,4887,25,مهندسي برق,دانشگاه صنعتي شيراز,1,90
18427,عطا میرزالو,خوي,10820,994,منطقه 3,1,5126,16,مهندسي کامپيوتر,دانشگاه اروميه,1,90
18428,نسرین پروز,ياسوج,10827,995,منطقه 3,4,5051,63,مهندسي کامپيوتر - بومي کهگيلويه وبويراحمد,دانشگاه تربيت دبير شهيد رجايي_تهران,1,90
18429,حسن عظیمی سوران,رباط كريم,10843,998,منطقه 3,2,5062,44,,,1,90
18430,احسان محمدنژادزیردهی,قرچك,10843,998,منطقه 3,1,5495,12,مهندسي مواد و متالورژي,دانشگاه علم و صنعت ايران - تهران,1,90